# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Unlockdown Horeca
email: peter@forret.com
description: > # this means to ignore newlines until "baseurl:"
    Help your horeca
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: pforret
github_username:  pforret
remote_theme : "manid2/lone-wolf-theme" 

# Build settings
markdown: kramdown

collections:
  resto:
    output: true